# Basic coturn configuration for testing
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=0.0.0.0
fingerprint
lt-cred-mech
realm=vchat
user=demo:demo1234
# Use long-term authentication and static user for testing only
# For production use secure credentials and deploy on a server with a public IP
no-multicast-peers
verbose
